### ISSUE TITLE
Remove 'www' from http://www.istherewaterintheriver.com/

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/water-in-the-river#8]
So it's easier to type and more funny.

**Comment by Faeranne** [comment]
We will need a www redirector, unless Carlos can make that happen without an external service.  I know of one that could be used.

**Comment by chimchim237** [comment]
I can do it; I just need to brush up on my DNS.  I'll have time tonight to take a look at it.

**Comment by groovecoder** [comment]
@chimchim237 - did you say you were able to fix this?

**Comment by chimchim237** [comment]
Yes!
